name: tiledbvcf-py
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pybind11>=2.5
  - pyarrow
  - dask>=0.19.0
  - pip
  - setuptools
  - setuptools_scm
  - setuptools_scm_git_archive
  - pytest-runner>=5.1
  - pytest>=5.1.2
  - zipp<3.16
