name: Nightly build against nightly libtiledb
on:
  push:
    paths:
      - '.github/workflows/nightly.yml'
  pull_request:
    paths:
      - '.github/workflows/nightly.yml'
  schedule:
    - cron: "0 3 * * *" # Every night at 3 AM UTC (10 PM EST; 11 PM EDT)
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone TileDB
        uses: actions/checkout@v3
        with:
          repository: TileDB-Inc/TileDB
          ref: dev
          path: TileDB
      - name: Clone TileDB-VCF
        uses: actions/checkout@v3
        with:
          path: TileDB-VCF
      - name: Build libtiledb
        run: |
          cmake -S TileDB -B build-libtiledb \
            -D TILEDB_WERROR=ON \
            -D TILEDB_SERIALIZATION=ON \
            -D CMAKE_BUILD_TYPE=Release
          cmake --build build-libtiledb -j2 --config Release
          cmake --build build-libtiledb -j2 --config Release --target install-tiledb
      - name: Build libtiledbvcf
        run: |
          cmake -S TileDB-VCF -B build-libtiledbvcf \
            -D CMAKE_BUILD_TYPE=Release
          cmake --build build-libtiledbvcf -j2 --config Release
          cmake --build build-libtiledbvcf -j2 --config Release --target install-libtiledbvcf
      - name: Build tiledbvcf-py
        run: |
          cd TileDB-VCF/apis/python
          python setup.py install
