name: Nightly build against nightly libtiledb
on:
  push:
    paths:
      - '.github/workflows/nightly.yml'
  pull_request:
    paths:
      - '.github/workflows/nightly.yml'
  schedule:
    - cron: "0 3 * * *" # Every night at 3 AM UTC (10 PM EST; 11 PM EDT)
  workflow_dispatch:
defaults:
  run:
    # Use default bash (plus -x to echo commands)
    shell: bash --noprofile --norc -eo pipefail -x {0}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-libtiledb-${{ matrix.libtiledb_version }}
    strategy:
      fail-fast: false
      matrix:
        libtiledb_version: [release-2.16, dev]
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Clone TileDB
        uses: actions/checkout@v3
        with:
          repository: TileDB-Inc/TileDB
          ref: ${{ matrix.libtiledb_version }}
          path: TileDB
      - name: Clone TileDB-VCF
        uses: actions/checkout@v3
        with:
          path: TileDB-VCF
      - name: Setup
        run: |
          mkdir installed
      - name: Setup conda env
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: TileDB-VCF/apis/python/conda-env.yml
          cache-environment: true
      - name: Setup macOS
        if: matrix.os == 'macos-latest'
        run: |
          # to build htslib from source
          brew install autoconf automake
      - name: Build libtiledb
        run: |
          set -x
          cmake -S TileDB -B build-libtiledb \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_INSTALL_PREFIX:PATH=$GITHUB_WORKSPACE/installed/ \
            -D TILEDB_WERROR=ON \
            -D TILEDB_SERIALIZATION=ON
          cmake --build build-libtiledb -j2 --config Release
          cmake --build build-libtiledb --config Release --target install-tiledb
      - name: Build libtiledbvcf
        run: |
          cmake -S TileDB-VCF/libtiledbvcf -B build-libtiledbvcf \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_INSTALL_PREFIX:PATH=$GITHUB_WORKSPACE/installed/ \
            -D OVERRIDE_INSTALL_PREFIX=OFF
          cmake --build build-libtiledbvcf -j2 --config Release
          cmake --build build-libtiledbvcf --config Release --target install-libtiledbvcf
          $GITHUB_WORKSPACE/installed/bin/tiledbvcf version
      - name: Build tiledbvcf-py
        # activate conda env to build Python package
        shell: bash -elx {0}
        run: |
          which python
          python --version
          cd TileDB-VCF/apis/python
          python setup.py install --libtiledbvcf=$GITHUB_WORKSPACE/installed/
          python -c "import tiledbvcf; print(tiledbvcf.version)"
  issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: build
    if: ( failure() || cancelled() ) && github.repository_owner == 'TileDB-Inc' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
      - name: Open Issue
        uses: TileDB-Inc/github-actions/open-issue@main
        with:
          name: nightly build
          label: nightly-failure
          assignee: awenocur,gspowley,ihnorton,Shelnutt2
        env:
          TZ: "America/New_York"
