name: Build Python client for Windows
on:
  push:
    branches:
      - main
      - 'release-*'
    paths:
      - '.github/workflows/windows.yml'
      - 'apis/python/**'
      - 'ci/*.bat'
      - 'ci/gha-win-env.yml'
      - 'libtiledbvcf/**'
  pull_request:
    paths:
      - '.github/workflows/windows.yml'
      - 'apis/python/**'
      - 'ci/*.bat'
      - 'ci/gha-win-env.yml'
      - 'libtiledbvcf/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch everything for python setuptools_scm
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install libtiledbvcf
        shell: bash
        run: |
          mkdir -p apis\python\dist_links\libtiledbvcf\build
          cd apis\python\dist_links\libtiledbvcf\build
          cmake ..
          cmake --build . -j2
          cmake --build . --target install-libtiledbvcf
      - name: Install tiledbvcf-py
        run: |
          cd apis\python
          python -m pip install -v .[test,dev]
      - name: tiledbvcf-py version
        run: python -c "import tiledbvcf; print(tiledbvcf.version)"
      - name: Test
        run: pytest apis\python\tests
